### ISSUE TITLE
Thermostat heating mode (0,1,2,3)

### ISSUE THREAD

**Issue by aschmidt74** [SeydX/homebridge-tado-platform#10]
I'd like to see (and serverside log) the actual heating activity.
It's shown in the tado app with none, or a 1-3 wave-symbol.
Hope this information is accessible.

**Comment by SeydX** [comment]
Added in v5

**Comment by SeydX** [comment]
Hey, i opened a new issue with instructions to test the beta version!

https://github.com/SeydX/homebridge-tado-platform/issues/16

**Comment by SeydX** [comment]
added in v5
