### ISSUE TITLE
Show battery status

### ISSUE THREAD

**Issue by tomsteenbakkers** [SeydX/homebridge-tado-platform#102]
Hi,

First: compliments for this plugin. It's beter than the HomeKit integration from Tado.

I have configured all 9 Todo thermostats and everything is working. The only thing is that I can not see the battery status. In the Home app it is not there. In the Eve app it shows always 100%. Is there a way in this plugin to show the actual battery status?

**Comment by UKenGB** [comment]
Same problem here. Battery accessory doesn't show in Home.app MacOS nor iOS and although it does show in Homebridge, it is always 100%.

Would be useful if it could be seen in Home.app and was accurate, but as it is, might as well disable it.
