### ISSUE TITLE
Separate Humidity sensors

### ISSUE THREAD

**Issue by nielsth** [SeydX/homebridge-tado-platform#11]
Currently, with the basic tado (v3/v3+) HomeKit integration the humidity levels are displayed under details of the thermostat / radiator valve. With this plug-in, the room temperature can be added as a temperature sensor and humidity is shown under details. 

Could an option be added to this plug-in to add separate humidity sensors in each room? This would make it possible to have the humidity displayed in the Home status report and read the value straight from the tile in the Home app, and saves a force / long press to the details screen.

Ideally, this would be an additional option in the plug-in, separate from the temperature sensor option.

**Comment by Sebastianwerner1985** [comment]
Is this already possible ? I read through the notes but I am not sure how to enable this! 
Would be awesome!

**Comment by DerPhil1992** [comment]
Think it is not possible in the current version. 
@SeydX would be great if you can add this feature in one future version of the plugin. Separate humidity sensors would be nice for me (and others, too).

**Comment by sneakinhysteria** [comment]
Same here, would love to see this. The slightly ambigious line under thermostats in the readme had me install this plugin as I hoped I could finally get a completely separate humidity sensor to trigger automations.

**Comment by Deltachaos** [comment]
Would love to see this as well

**Comment by SeydX** [comment]
Added to list #48

**Comment by SeydX** [comment]
Added in v6
