### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by jonalbr** [SeydX/homebridge-tado-platform#110]
Hi, I get the following error message for some time now:
`{"message":"Client request error: getaddrinfo EAI_AGAIN auth.tado.com","statusCode":502,"error":"Bad Gateway"}`

Anyone got any help on what is wrong? I didn't change anything in my configuration. As I originally configured the plugin, everything worked just fine.

Thanks a lot for any help!
Jonas

**Comment by MR91** [comment]
I have the same issue since today. Tried restarting my internet aswell as my homebridge with no success. Tado app is working fine, so their infrastructure doesnt seem to be the issue.

**Comment by NickZig** [comment]
Hi, i have the same problem since today :(

**Comment by bxlouis** [comment]
Same problem as of today.

**Comment by bxlouis** [comment]
It appears the issue was caused by my PiHole configuration. 
The client which hosts Homebridge was rate limited.
I followed the steps highlighted in [this thread](https://www.reddit.com/r/pihole/comments/osm2fn/psa_if_you_are_having_random_dns_resolution/) which immediately fixed the issue.

> Rate-limiting can easily be disabled by setting RATE_LIMIT=0/0 in /etc/pihole/pihole-FTL.conf. If I want, say, to set a rate limit of 1 query per hour, the option should look like RATE_LIMIT=1/3600.
