### ISSUE TITLE
iOS 16 beta: shows target temperature as current temperature

### ISSUE THREAD

**Issue by distantnative** [SeydX/homebridge-tado-platform#120]
On the iOS 16 beta in the new Home app, current temperatures are shown wrongly - simply displaying the target temperature again not the current temperature.

Unsure if this is a bug by the new Home app or if the plugin needs to be adapted for the new Home app.

**Comment by xyz667** [comment]
> On the iOS 16 beta in the new Home app, current temperatures are shown wrongly - simply displaying the target temperature again not the current temperature.
> Unsure if this is a bug by the new Home app or if the plugin needs to be adapted for the new Home app.

I can‘t test thoroughly in summer, but to me this seems to work in the current iOS beta (20A5328h)?

**Comment by distantnative** [comment]
I just checked again and indeed seems to be fixed by the newest iOS beta. 👍
