### ISSUE TITLE
Anyone-occupancy sensor detects motion

### ISSUE THREAD

**Issue by nielsth** [SeydX/homebridge-tado-platform#13]
Under the Details and Settings screens of the Anyone occupancy sensor the status label reads "Motion detected" (yes of no). For an occupancy sensor however, this should be "Occupancy detected".

Also, is it possible to show the number of people detected here? Or is that not possible within the HomeKit specs? 

![img_0015](https://user-images.githubusercontent.com/13969232/50759023-1af7fc80-1264-11e9-84c1-5a92d01704c2.png)
![img_0014](https://user-images.githubusercontent.com/13969232/50759022-1af7fc80-1264-11e9-8bfa-baac13337fa1.png)

**Comment by SeydX** [comment]
Im currently working on v5. Should be fixed now

**Comment by SeydX** [comment]
Hey, i opened a new issue with instructions to test the beta version!

https://github.com/SeydX/homebridge-tado-platform/issues/16

**Comment by SeydX** [comment]
should be fixed in v5
