### ISSUE TITLE
Error property athome null

### ISSUE THREAD

**Issue by rossco57** [SeydX/homebridge-tado-platform#14]
Keep getting error property athome null
Any help as to what this is

**Comment by rossco57** [comment]
The exact error is

Error occurred by getting user
TypeError cannot read property ‘athome’ of null

**Comment by SeydX** [comment]
Im currently working on v5. Should be fixed now

**Comment by SeydX** [comment]
Hey, i opened a new issue with instructions to test the beta version!

https://github.com/SeydX/homebridge-tado-platform/issues/16

**Comment by SeydX** [comment]
should be fixed in v5
