### ISSUE TITLE
Auto mode no longer available

### ISSUE THREAD

**Issue by henkhb** [SeydX/homebridge-tado-platform#15]
The auto mode disappeared from my thermostat. It was the main reason for using the plugin. :/
Tado changed API? Anybody with the same issue?

I have only hearing, cooling, off.

**Comment by SeydX** [comment]
Hey, im currently working on v5 and i dont have noticed any changes regarding to this issue. The auto mode is still there

**Comment by SeydX** [comment]
Hey, i opened a new issue with instructions to test the beta version!

https://github.com/SeydX/homebridge-tado-platform/issues/16

**Comment by SeydX** [comment]
should be fixed in v5

**Comment by henkhb** [comment]
Just upgraded to 5.0 and error is back. Any idea?

**Comment by flausen** [comment]
Same here
