### ISSUE TITLE
Change timer

### ISSUE THREAD

**Issue by adavison007** [SeydX/homebridge-tado-platform#19]
Running V5, nice... Two issues?

1) Hot Water not responding, nor does the heating thermostat (only thermostat with issue) that controls the hot water 

2) When changing the temperature in HomeKit, it sets the tado temp correctly, but makes the setting permanent (until next manual change), I'd like it to do it the same way as the tado app settings I have, which is change at next automatic setting change,

If you can advise that would be great?

**Comment by SeydX** [comment]
Hey @adavison007 

1. Thats a known bug, im already on this

2. That would be easy to write, added into my todo list

**Comment by adavison007** [comment]
Great news on both points, look forward to the update

**Comment by SeydX** [comment]
Hey, added a new parameter under devices in config.json (just update and restart homebridge and the config.json will be refreshed with additional parameter called "overrideMode")

overrideMode accepts two values (auto/manual). "auto" will change the temperature adjustment to "until next automatic change" and manual will change it to "until next manual change"

closing this issue, hot water bug already opened here

https://github.com/SeydX/homebridge-tado-platform/issues/18

**Comment by adavison007** [comment]
Just done this, perfect, works a treat, thank you so much...

Side question, since I updated the Homebridge UI to 5.0 today I have an error message, I can put the package.json back as it says I don't have permissions, if I change permissions it still does not work, any ideas? 
<img width="317" alt="Homebridge_Spinney" src="https://user-images.githubusercontent.com/47482260/56248837-91956900-60a1-11e9-8869-b4cd338eaa35.png">

**Comment by adavison007** [comment]
Ignore last comment, fixed 👍
