### ISSUE TITLE
Telegam funktion for open window detection

### ISSUE THREAD

**Issue by Krocko** [SeydX/homebridge-tado-platform#24]
Hi @SeydX. 
Is it possible for you to add the telegram feature for this plugin too?
Would be really nice. 
Thanks in advance.

**Comment by SeydX** [comment]
Will add this to my list thx

**Comment by Nastras** [comment]
Would be great with the revision of the plugin if you can install the telegram function also for the presence sensors as with the Fritz plugin 😉

**Comment by SeydX** [comment]
Added to list #48

**Comment by SeydX** [comment]
Added in v6
