### ISSUE TITLE
delaytimer

### ISSUE THREAD

**Issue by det-box** [SeydX/homebridge-tado-platform#3]
Hello,
give it or it will be in this plugin
also a 'delay timer': give option,
as in the old V3 version?

Thank you

**Comment by SeydX** [comment]
Its in the plugin, but not in config.json 

You can adjust the delay timer within a 3rd party App like Elgato Eve , all Thermostats has his own delaytimer
![f81d3a9b-bec1-4e80-9809-63b0761ed664](https://user-images.githubusercontent.com/34152761/39930732-c91c9370-553b-11e8-9bc4-dee644ae866a.png)

**Comment by det-box** [comment]
Hello,
Thanks for the answer.
Unfortunately, I do not use the EVE APP,
will it (is it planned) in the config.json to integrate ?

**Comment by SeydX** [comment]
But the function will be the same, with the Current Version we have the possibility to Set a delay timer for the thermostat we want to delay and Not for ALL Thermostats (config.json)

As i said, the function with the delay is the same as in v3

**Comment by det-box** [comment]
I can not follow now
one delay for all thermostats or one thermostat each
Delay.

It would be enough for me if the stub thermostat switches on with a delay, because there is the balcony door with it.

Where you can sometimes go in and out more often.

But a delay (as in V3) works too.
Thanks

**Comment by SeydX** [comment]
This new Version implements for every Thermostat his OWN delay timer. That means, you can adjust a different delay for each Thermostat within a 3rd party App like Elgato Eve etc

But the main function will be the same as in v3 Just with the difference that you can adjust an own delay for each Thermostat

**Comment by SeydX** [comment]
I will change the delay function in the next version

There will be also a 'Delay Switch' next to the 'Delay Slider'

So the Switch will control the Switch to make Automations based on the Switch to control the thermostat by opening a door or window

**Comment by det-box** [comment]
Ok, that's great. I'm waiting for the next version.

Thank you

**Comment by SeydX** [comment]
v4.3.1 is online with the new delay function

**Comment by SeydX** [comment]
I think we can Close this issue , if you get Problems with the new delay function, feel Free to re open the issue

**Comment by djrams10** [comment]
Hello, is it possible to delay more than 120 seconds? thanks
