### ISSUE TITLE
New features in the Android app(pollen dispersal & air quality)

### ISSUE THREAD

**Issue by senger1985** [SeydX/homebridge-tado-platform#30]
How is it possible to query these values?

**Comment by adavison007** [comment]
@SeydX was going to ask the same, can we get these into home bridge? 
![IMG_6351](https://user-images.githubusercontent.com/47482260/64440867-aca25d00-d0c4-11e9-9690-a6900bd14c09.png)
![IMG_6350](https://user-images.githubusercontent.com/47482260/64440872-add38a00-d0c4-11e9-910f-1ad35753760e.png)

**Comment by adamrzanek** [comment]
Wow it would be great too expose that info in HomeKit

**Comment by SeydX** [comment]
Added to list #48

**Comment by SeydX** [comment]
Added in v6
