### ISSUE TITLE
Changing Temperature in ios13

### ISSUE THREAD

**Issue by adavison007** [SeydX/homebridge-tado-platform#32]
When the setting is "Auto" and you change the temperature to a new setting in homekit it automatically ignores the new temperature and goes back to the auto set temperature... can you make the plugins automatically change th temperature to the set temperature and update to heating or cooling but if the setting is auto allow the system to change with the next update... it's so annoying to have to change the setting to heating in homekit and then set the temperature....

**Comment by jasehigh** [comment]
The upgrade to iOS13 has had a very negative effect on this previously perfect plugin. Even if I change the mode the :heat: first and then adjust the temperature, the radiator will quick go back to "auto" mode, cancelling the temperature change requested.

**Comment by adavison007** [comment]
> When the setting is "Auto" and you change the temperature to a new setting in homekit it automatically ignores the new temperature and goes back to the auto set temperature... can you make the plugins automatically change th temperature to the set temperature and update to heating or cooling but if the setting is auto allow the system to change with the next update... it's so annoying to have to change the setting to heating in homekit and then set the temperature....
---------

**THIS IS AN ISSUE....** So if you change the temperature whilst in auto it keeps going back to the set auto temperature.... it does not keep the new temperature set in homekit (as it should) and only revert back to the auto temp at the next time change set in the the tado app.

**Please can this be fixed?**

**Comment by adavison007** [comment]
@SeydX hi, any news on this issue?

**Comment by adavison007** [comment]
@SeydX hi, any news on this issue?

**Comment by adavison007** [comment]
Sorry to be a pain @SeydX  but are you able to fix this issue?

**Comment by adavison007** [comment]
@SeydX I am happy to donate to get this fixed? please advise.... I love your plugin, but it's not usable since iOS 13, really keen for a fix and happy to pay!!!!

**Comment by adavison007** [comment]
@SeydX  will this issue be fixed? Need to find an alternative way to do Tado if not? Please advise, this app is amazing, but need to be able to change temprature

**Comment by adavison007** [comment]
@SeydX have you stopped working on this project?

**Comment by SeydX** [comment]
Will be fixed with v6 #48

**Comment by SeydX** [comment]
Fixed in v6
