### ISSUE TITLE
delay switch unit

### ISSUE THREAD

**Issue by MaurizioB84** [SeydX/homebridge-tado-platform#33]
Hello,

I want to understand the unit of delay switch and how i can configure it via config.json (if it's possible)

many thanks

**Comment by SeydX** [comment]
Delay: Every thermostat has two options (if extendedDelay setted to true in config.json) which are accessible over 3rd party apps like Elgato EVE etc - Delay Switch and Delay Timer. If delay timer > 0 and you turn on delay switch, the delay timer will begin to run and after the time is up, the switch will automatically turn off. (Thats helpfull for creating automations which needs a delay for turning on/off)
