### ISSUE TITLE
Polling frequency

### ISSUE THREAD

**Issue by theGeorg** [SeydX/homebridge-tado-platform#34]
How does the polling setting work? For me it seams no matter how i change it is polling every few seconds. Since I only want my temperature data recorded in the eve app i would like to change that to only poll one every few minutes. 

Kind regards

**Comment by muratcorlu** [comment]
@theGeorg did you find any solution or workaround?

I'm using AdGuard as a DNS proxy in my network. And noticed that this plugin makes huge amount of dns query for my.tado.com 

![image](https://user-images.githubusercontent.com/127687/86172682-15106e00-bb1f-11ea-8a66-628ee9781f02.png)

And I'm sure that those requests are coming from my RaspberryPi:

![image](https://user-images.githubusercontent.com/127687/86172787-383b1d80-bb1f-11ea-8218-185dbbd44152.png)

![image](https://user-images.githubusercontent.com/127687/86172868-5274fb80-bb1f-11ea-8594-1cc2ab3cec23.png)

There is really something wrong here and increasing `polling` value didn't help.

**Comment by muratcorlu** [comment]
Any comments about this? @SeydX Is this related with polling config or is it accepted situation to have that much DNS queries for 7 valve thermostats and 1 wall thermostat?

![image](https://user-images.githubusercontent.com/127687/86769169-05c57f00-c04f-11ea-8029-d6e2d2bb4249.png)

**Comment by SeydX** [comment]
Will be fixed with v6 #48

**Comment by mpjalexander** [comment]
I've noticed the same with my pi-hole setup (many queries per second).

Also, I read [on Facebook](https://www.facebook.com/groups/566132154209224/permalink/881712462651190/) that tado are changing some of their back-end APIs to limit the frequency of requests. @SeydX, are you aware of these changes?

**Comment by SeydX** [comment]
> Also, I read [on Facebook](https://www.facebook.com/groups/566132154209224/permalink/881712462651190/) that tado are changing some of their back-end APIs to limit the frequency of requests. @SeydX, are you aware of these changes?

Do you have more infos about this?

**Comment by mpjalexander** [comment]
![image](https://user-images.githubusercontent.com/17403475/110202706-63220200-7e62-11eb-942f-1d813c959cca.jpeg)

**Comment by mpjalexander** [comment]
I've asked if anyone can provide further details via the Facebook group.

**Comment by danbayliss** [comment]
Probably worth reaching out directly to Tado. Reading the Home Assistant pull request it looks like they have plans to rate limit the polling - https://github.com/home-assistant/core/pull/46915

**Comment by SeydX** [comment]
Fixed in v6
