### ISSUE TITLE
Window Sensors only react on Tado App Confirmation

### ISSUE THREAD

**Issue by jotzet79** [SeydX/homebridge-tado-platform#37]
I enabled the setting in Homebridge's config.json, and in the settings in the Tado app, according to @SeydX ReadMe / HowTo; But my sensors seem to be only working if I press actively "Open Window detected in Room X", then it the sensor changes its state. Is this the normal behaviour?
Thx for the great work,
Jo

> Window sensors:
> If enabled in config.json (openWindow) AND under the setting in the tado app (open window detection), this plugin creates window sensors for each room. So if the Tado open window detection detects an open window, the sensor will go on, and if the open window goes off, the sensor will also goes off
>

**Comment by jlnbln** [comment]
I am having the same problem. Any chance this can be fixed? Would be nice to not have to pay for tados subscription...

I did some research and found this on another tado plugin: https://github.com/lukasroegner/homebridge-tado-smart-thermostat/issues/10 

It talks about the difference of WindowOpen state and WindowOpenDetect. Any Chance we have a similar problem here? 

Love the tado plugin and don't want to change, but windowOpen Sensors were originally the reason why I started to use the plugin in the first place.

**Comment by SeydX** [comment]
Will be fixed with v6 #48

**Comment by jotzet79** [comment]
Hello @SeydX ,
Good to see you back! ;) 

regarding this feature I also summed up the needed steps here https://github.com/lukasroegner/homebridge-tado-smart-thermostat/issues/38#issue-803052989

**Comment by SeydX** [comment]
Should be fixed in v6
