### ISSUE TITLE
@seydx are you still actively working this plugin?

### ISSUE THREAD

**Issue by adavison007** [SeydX/homebridge-tado-platform#38]
Sorry to bug, trying to work out where I go now that the iOS 13 has caused issues with working Tado via HomeKit, please can you advise if you are continuing to develop this app? I, like others love what you’ve done and appreciate the effort, please advise? Thanks

**Comment by SeydX** [comment]
I will update this plugin very soon

**Comment by mtressl** [comment]
Really?

**Comment by jotzet79** [comment]
Maybe forces can be joined between @SeydX and @lukasroegner who was developing a new plugin for homebridge?
