### ISSUE TITLE
Homebridge error when trying to read tado hot water temperature

### ISSUE THREAD

**Issue by weegza** [SeydX/homebridge-tado-platform#4]
Hi, the module errors when my hot water is on:

[2018-7-6 16:40:53] [Tado] [ERROR] Utility Room BU3181906432: An error occured by getting boiler state, trying again...                      
[2018-7-6 16:40:53] [Tado] [ERROR] TypeError: Cannot read property 'celsius' of null  

I think this is because of my Tado system - it heats my hot water but it doesnt measure the temperature of the water - my boiler does that itself.

**Comment by mpjalexander** [comment]
I have the same issue. I also have a water heater that’s effectively a simple “on” or “off”, which Tado recognises in the app as such. 

![2e953666-37c7-4fca-925a-1a8c99387c27](https://user-images.githubusercontent.com/17403475/43354778-27fac5b0-924a-11e8-8c75-1ca324d2ec65.png)

I love this plug-in. If it could handle my type of hot water system it would be near perfect.

I’d be happy to help diagnose the issue and help resolve it.

**Comment by jasehigh** [comment]
Same issue here. My boiler is on/off only. Tado does not recognise the the temperature settings this plugin provides. An option to make the boiler a simple... on/off/auto option would be fantastic.

**Comment by mpjalexander** [comment]
@SeydX, is there anything I can do to help resolve this issue? I’m happy to install any test version and report back.

**Comment by SeydX** [comment]
Hello, sry im answering late, currently working on v5 and this is fixed now, wait for v5

**Comment by jasehigh** [comment]
Great news... look forward to testing v5.

**Comment by SeydX** [comment]
Hey, i opened a new issue with instructions to test the beta version!

https://github.com/SeydX/homebridge-tado-platform/issues/16

**Comment by SeydX** [comment]
should be fixed in v5
