### ISSUE TITLE
Bump dependencies for latest Homebridge version 1.0.x

### ISSUE THREAD

**Issue by mtressl** [SeydX/homebridge-tado-platform#41]
Hi
would be great to have this plugin working as expected due to the latest Homebridge update.

`[4/28/2020, 8:14:50 AM] The plugin "homebridge-tado-platform" requires a Homebridge version of ^0.4.46 which does not satisfy the current Homebridge version of 1.0.2. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stablity problems running this plugin.`

Thanks!

**Comment by MaurizioB84** [comment]
Hello, I ask the same, can you please update the plugin?

thanks

**Comment by mtressl** [comment]
bump

**Comment by krystof0778** [comment]
Bump, getting same issue as mtressi...

**Comment by mtressl** [comment]
@krystof0778 
I migrated to https://github.com/lukasroegner/homebridge-tado-smart-thermostat which works pretty much the same, no issues since 2+ weeks. You might want to take a look.

**Comment by bnSonic** [comment]
Same Problem here:

npm WARN deprecated simple-oauth2@2.5.2: simple-oauth2 v2 is no longer supported. Please upgrade to v3 for further support
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated wreck@14.2.0: This module has moved and is now available at @hapi/wreck. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated bourne@1.1.2: This module has moved and is now available at @hapi/bourne. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated hoek@6.1.3: This module has moved and is now available at @hapi/hoek. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.
npm WARN deprecated boom@7.3.0: This module has moved and is now available at @hapi/boom. Please update your dependencies as this version is no longer maintained an may contain bugs and security issues.

And Log:

The plugin "homebridge-tado-platform" requires a Homebridge version of ^0.4.46 which does not satisfy the current Homebridge version of 1.2.3. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.
[11/6/2020, 9:16:51 PM] The plugin "homebridge-tado-platform" requires Node version of ^10.15.3 which does not satisfy the current Node version of v14.15.0. You may need to upgrade your installation of Node.

**Comment by mtressl** [comment]
Move over to https://github.com/lukasroegner/homebridge-tado-smart-thermostat @bnSonic - no problems at all on my side and uptodate.

**Comment by bnSonic** [comment]
> Move over to https://github.com/lukasroegner/homebridge-tado-smart-thermostat @bnSonic - no problems at all on my side and uptodate.

Strange - see my issue there: https://github.com/lukasroegner/homebridge-tado-smart-thermostat/issues/22 - it is running and it works but i don't have the best feeling with that.

(i'm running Homebridte 1.2.3 on my Synology in Docker)
Homebridge: v1.2.3
OS	Alpine Linux (3.12.1)
Node.js Version	v14.15.0
Npm Version	v6.14.8
Docker	Yes
Service-Modus	Yes
