### ISSUE TITLE
Axios outdated

### ISSUE THREAD

**Issue by WinfriedO** [SeydX/homebridge-tado-platform#44]
I'm new to homebridge. During configuration of Hoobs on my raspberry I got a message that there is some vulunerability or something like this related to axios and tado platform. I tried to let it fix by $sudo npm audit fix, but was not successful. I uninstalled tado an then npm audit found no problem. 
How do I get tado installed without this "axios" problem?

**Comment by SeydX** [comment]
Will be fixed with v6 #48

**Comment by SeydX** [comment]
Fixed in v6
