### ISSUE TITLE
[ERROR] Can not refresh devices!

### ISSUE THREAD

**Issue by MexxReal** [SeydX/homebridge-tado-platform#45]
Actually I have the problem that the error message '[ERROR] Can not refresh devices!' is shown.
A restart of the tado bridge and the homebridge did not change anything.

I use Hoobs as a Docker image, but so far this has not caused any problems.

After restart the following information is displayed:
19.1.2021, 15:02:13 [TadoPlatform] [INFO] Configuring accessory living room RU2929790720
19.1.2021, 15:02:13 [TadoPlatform] [INFO] Configuring accessory living room VA1559299584
19.1.2021, 15:02:13 [TadoPlatform] [INFO] Configuring accessory bathroom VA2698774016
19.1.2021, 15:02:13 [TadoPlatform] [INFO] Configuring accessory bedroom RU1235422976
19.1.2021, 15:02:13 [TadoPlatform] [INFO] Configuring accessory bedroom VA2090862336
19.1.2021, 15:02:13 [TadoPlatform] [INFO] Configuring accessory kitchen VA3310028032
19.1.2021, 15:02:13 [TadoPlatform] [INFO] Configuring accessory study RU2880112640
19.1.2021, 15:02:13 [TadoPlatform] [INFO] Configuring accessory study VA3930785024

However, all my automations are currently not working.

How can I check where the problem is located and maybe fix it?

**Comment by MexxReal** [comment]
I tried to renew the configuration, but it's ending like before.
Nothing worked until now. I chose 'reconfigured: true', reset the config.json, etc.  

25.1.2021, 20:47:45 [TadoPlatform] [INFO] Adding new accessory: Wohnzimmer RU2929790720
25.1.2021, 20:47:48 [TadoPlatform] [INFO] Adding new accessory: Wohnzimmer VA1559299584
25.1.2021, 20:47:48 [TadoPlatform] [INFO] Adding new accessory: Badezimmer VA2698774016
25.1.2021, 20:47:48 [TadoPlatform] [INFO] Adding new accessory: Schlafzimmer RU1235422976
25.1.2021, 20:47:48 [TadoPlatform] [INFO] Adding new accessory: Schlafzimmer VA2090862336
25.1.2021, 20:47:48 [TadoPlatform] [INFO] Adding new accessory: Küche VA3310028032
25.1.2021, 20:47:48 [TadoPlatform] [INFO] Adding new accessory: Arbeitszimmer RU2880112640
25.1.2021, 20:47:48 [TadoPlatform] [INFO] Adding new accessory: Arbeitszimmer VA3930785024
25.1.2021, 20:48:28 [TadoPlatform] [ERROR] Can not refresh zones!
25.1.2021, 20:48:48 [TadoPlatform] [ERROR] Can not refresh devices!
25.1.2021, 20:49:08 [TadoPlatform] [ERROR] Can not refresh devices!
25.1.2021, 20:49:28 [TadoPlatform] [ERROR] Can not refresh devices!
25.1.2021, 20:49:48 [TadoPlatform] [ERROR] Can not refresh devices!
25.1.2021, 20:50:08 [TadoPlatform] [ERROR] Can not refresh devices!
25.1.2021, 20:50:28 [TadoPlatform] [ERROR] Can not refresh devices!
25.1.2021, 20:50:48 [TadoPlatform] [ERROR] Can not refresh devices!

Do you have any idea what to do?

**Comment by adavison007** [comment]
Move to this one 
homebridge-tado-smart-thermostat


Adam Davison
adavison@me.com <mailto:adavison@me.com>
01276 63145
07748 761448

On 25 Jan 2021, at 19:55, MexxReal <notifications@github.com> wrote:


I tried to renew the configuration, but it's ending like before.
Nothing worked until now. I chose 'reconfigured: true', reset the config.json, etc.

25.1.2021, 20:47:45 [TadoPlatform] [INFO] Adding new accessory: Wohnzimmer RU2929790720
25.1.2021, 20:47:48 [TadoPlatform] [INFO] Adding new accessory: Wohnzimmer VA1559299584
25.1.2021, 20:47:48 [TadoPlatform] [INFO] Adding new accessory: Badezimmer VA2698774016
25.1.2021, 20:47:48 [TadoPlatform] [INFO] Adding new accessory: Schlafzimmer RU1235422976
25.1.2021, 20:47:48 [TadoPlatform] [INFO] Adding new accessory: Schlafzimmer VA2090862336
25.1.2021, 20:47:48 [TadoPlatform] [INFO] Adding new accessory: Küche VA3310028032
25.1.2021, 20:47:48 [TadoPlatform] [INFO] Adding new accessory: Arbeitszimmer RU2880112640
25.1.2021, 20:47:48 [TadoPlatform] [INFO] Adding new accessory: Arbeitszimmer VA3930785024
25.1.2021, 20:48:28 [TadoPlatform] [ERROR] Can not refresh zones!
25.1.2021, 20:48:48 [TadoPlatform] [ERROR] Can not refresh devices!
25.1.2021, 20:49:08 [TadoPlatform] [ERROR] Can not refresh devices!
25.1.2021, 20:49:28 [TadoPlatform] [ERROR] Can not refresh devices!
25.1.2021, 20:49:48 [TadoPlatform] [ERROR] Can not refresh devices!
25.1.2021, 20:50:08 [TadoPlatform] [ERROR] Can not refresh devices!
25.1.2021, 20:50:28 [TadoPlatform] [ERROR] Can not refresh devices!
25.1.2021, 20:50:48 [TadoPlatform] [ERROR] Can not refresh devices!

Do you have any idea what to do?

**Comment by MexxReal** [comment]
@adavison007 this one doesn't work with hoobs. I tried.

@SeydX Actually everything is working fine. Could this error based on a low battery status? Because I had to change them in two devices...

**Comment by SeydX** [comment]
Will be fixed with v6 #48

**Comment by SeydX** [comment]
Fixed in v6
