### ISSUE TITLE
Central Switch cannot be activated

### ISSUE THREAD

**Issue by kaosmagix** [SeydX/homebridge-tado-platform#5]
I enabled the Central Switch with the goal to periodically force all thermostats back to Auto mode. Tis as worked for a period of time, but now the button acts as if it is stateless (i.e. I can activate the button but it is directly turned off again). It also doesn't reset te thermostats to auto mode.

Related question: My central config setting for Tado is to revert to auto when te next scheduled event happens. However is seems that a manual change in Homekit sets it to Active until cancelled by user, this should not happen.

**Comment by SeydX** [comment]
Im currently working on v5. Should be fixed now

**Comment by SeydX** [comment]
Hey, i opened a new issue with instructions to test the beta version!

https://github.com/SeydX/homebridge-tado-platform/issues/16

**Comment by SeydX** [comment]
should be fixed in v5
