### ISSUE TITLE
Raumthermostate von Drittanbietern

### ISSUE THREAD

**Issue by Paddy03161** [SeydX/homebridge-tado-platform#51]
Hi, 
erstmal vielen Dank für das große Update! 
Mich würde interessieren ob es möglich ist Raumthermostate von anderen Herstellern (z.B. Aqara) anstatt der internen Temperaturmessung der Tado Heizkörperthermostate zu nutzen. Also einen Ersatz für die Tado Raumthermostate. 

Gruß
Patrick

**Comment by SeydX** [comment]
Hallo @Paddy03161 

das Plugin funktioniert nur mit Thermostaten von Tado
