### ISSUE TITLE
Target temperature is rounded

### ISSUE THREAD

**Issue by benidi** [SeydX/homebridge-tado-platform#52]
If target temperature is set to 19.5 in the tado app in homekit is 20.0 displayed. Is it possible to show the decimal value in homekit?
![IMG_1008](https://user-images.githubusercontent.com/16839129/111278842-5196e200-863a-11eb-8d04-dab994e3c51f.jpeg)
![IMG_1009](https://user-images.githubusercontent.com/16839129/111278845-522f7880-863a-11eb-879f-70808175cfd8.jpeg)

**Comment by SeydX** [comment]
Added support in v6.0.6

Please refresh your config.json

See here: https://github.com/SeydX/homebridge-tado-platform/blob/7f5d0da0278a5b22b958a78bab05552e7e946b14/example-config.json#L140

**Comment by benidi** [comment]
Thank you very much! Works perfect. Very nice plugin. Much better than the direct integration from Tado. 👍
