### ISSUE TITLE
Schedule Status doesn't get reflected within Homekit

### ISSUE THREAD

**Issue by spooky82** [SeydX/homebridge-tado-platform#53]
It seems that the Homekit Switch for Schedule doesn't reflect the current state of the tado system.

**Comment by SeydX** [comment]
@spooky82 

What u mean exactly?

**Comment by spooky82** [comment]
I mean that it's not visible within HomeKit wether tado is in automatic mode or not.

Example: although I manually changed the temperature of a thermostat, the switch is still showing that the automatic mode is on.

**Comment by SeydX** [comment]
@spooky82 

can u post your config.json pls

**Comment by spooky82** [comment]
@SeydX 

Sure - here you go:

{
    "platform": "TadoPlatform",
    "name": "TadoPlatform",
    "homes": [
        {
            "zones": [
                {
                    "mode": "AUTO",
                    "openWindowSwitch": false,
                    "name": "Diele",
                    "active": true,
                    "noBattery": false,
                    "id": 12,
                    "type": "HEATING",
                    "accTypeBoiler": "SWITCH",
                    "boilerTempSupport": false,
                    "modeTimer": 30,
                    "separateTemperature": false,
                    "separateHumidity": true,
                    "autoOffDelay": false,
                    "openWindowSensor": false,
                    "easyMode": false,
                    "airQuality": false,
                    "delaySwitch": false
                },
                {
                    "mode": "AUTO",
                    "openWindowSwitch": false,
                    "name": "Bad Erdgeschoss",
                    "active": true,
                    "noBattery": false,
                    "id": 13,
                    "type": "HEATING",
                    "accTypeBoiler": "SWITCH",
                    "boilerTempSupport": false,
                    "modeTimer": 30,
                    "separateTemperature": false,
                    "separateHumidity": true,
                    "autoOffDelay": false,
                    "openWindowSensor": false,
                    "easyMode": false,
                    "airQuality": false,
                    "delaySwitch": false
                },
                {
                    "mode": "AUTO",
                    "openWindowSwitch": false,
                    "name": "Wohnzimmer",
                    "active": true,
                    "noBattery": false,
                    "id": 11,
                    "type": "HEATING",
                    "accTypeBoiler": "SWITCH",
                    "boilerTempSupport": false,
                    "modeTimer": 30,
                    "separateTemperature": false,
                    "separateHumidity": true,
                    "autoOffDelay": false,
                    "openWindowSensor": true,
                    "easyMode": false,
                    "airQuality": false,
                    "delaySwitch": false
                },
                {
                    "mode": "AUTO",
                    "openWindowSwitch": false,
                    "name": "Laras Zimmer",
                    "active": true,
                    "noBattery": false,
                    "id": 15,
                    "type": "HEATING",
                    "accTypeBoiler": "SWITCH",
                    "boilerTempSupport": false,
                    "modeTimer": 30,
                    "separateTemperature": false,
                    "separateHumidity": true,
                    "autoOffDelay": false,
                    "openWindowSensor": true,
                    "easyMode": false,
                    "airQuality": false,
                    "delaySwitch": false
                },
                {
                    "mode": "AUTO",
                    "openWindowSwitch": false,
                    "name": "Spielzimmer",
                    "active": true,
                    "noBattery": false,
                    "id": 8,
                    "type": "HEATING",
                    "accTypeBoiler": "SWITCH",
                    "boilerTempSupport": false,
                    "modeTimer": 30,
                    "separateTemperature": false,
                    "separateHumidity": true,
                    "autoOffDelay": false,
                    "openWindowSensor": true,
                    "easyMode": false,
                    "airQuality": false,
                    "delaySwitch": false
                },
                {
                    "mode": "AUTO",
                    "openWindowSwitch": false,
                    "name": "Raphis Zimmer",
                    "active": true,
                    "noBattery": false,
                    "id": 9,
                    "type": "HEATING",
                    "accTypeBoiler": "SWITCH",
                    "boilerTempSupport": false,
                    "modeTimer": 30,
                    "separateTemperature": false,
                    "separateHumidity": true,
                    "autoOffDelay": false,
                    "openWindowSensor": true,
                    "easyMode": false,
                    "airQuality": false,
                    "delaySwitch": false
                },
                {
                    "mode": "AUTO",
                    "openWindowSwitch": false,
                    "name": "Büro",
                    "active": true,
                    "noBattery": false,
                    "id": 1,
                    "type": "HEATING",
                    "accTypeBoiler": "SWITCH",
                    "boilerTempSupport": false,
                    "modeTimer": 30,
                    "separateTemperature": false,
                    "separateHumidity": true,
                    "autoOffDelay": false,
                    "openWindowSensor": true,
                    "easyMode": false,
                    "airQuality": false,
                    "delaySwitch": false
                },
                {
                    "mode": "AUTO",
                    "openWindowSwitch": false,
                    "name": "Bad Obergeschoss",
                    "active": true,
                    "noBattery": false,
                    "id": 10,
                    "type": "HEATING",
                    "accTypeBoiler": "SWITCH",
                    "boilerTempSupport": false,
                    "modeTimer": 30,
                    "separateTemperature": false,
                    "separateHumidity": true,
                    "autoOffDelay": false,
                    "openWindowSensor": true,
                    "easyMode": false,
                    "airQuality": false,
                    "delaySwitch": false
                },
                {
                    "mode": "AUTO",
                    "openWindowSwitch": false,
                    "name": "Schlafzimmer",
                    "active": true,
                    "noBattery": false,
                    "id": 2,
                    "type": "HEATING",
                    "accTypeBoiler": "SWITCH",
                    "boilerTempSupport": false,
                    "modeTimer": 30,
                    "separateTemperature": false,
                    "separateHumidity": true,
                    "autoOffDelay": false,
                    "openWindowSensor": true,
                    "easyMode": false,
                    "airQuality": false,
                    "delaySwitch": false
                },
                {
                    "mode": "AUTO",
                    "openWindowSwitch": false,
                    "name": "Bad Dachgeschoss",
                    "active": true,
                    "noBattery": false,
                    "id": 3,
                    "type": "HEATING",
                    "accTypeBoiler": "SWITCH",
                    "boilerTempSupport": false,
                    "modeTimer": 30,
                    "separateTemperature": false,
                    "separateHumidity": true,
                    "autoOffDelay": false,
                    "openWindowSensor": true,
                    "easyMode": false,
                    "airQuality": false,
                    "delaySwitch": false
                },
                {
                    "mode": "AUTO",
                    "openWindowSwitch": false,
                    "name": "Garderobe",
                    "active": true,
                    "noBattery": false,
                    "id": 4,
                    "type": "HEATING",
                    "accTypeBoiler": "SWITCH",
                    "boilerTempSupport": false,
                    "modeTimer": 30,
                    "separateTemperature": false,
                    "separateHumidity": true,
                    "autoOffDelay": false,
                    "openWindowSensor": true,
                    "easyMode": false,
                    "airQuality": false,
                    "delaySwitch": false
                },
                {
                    "mode": "AUTO",
                    "openWindowSwitch": false,
                    "name": "Hobbyraum",
                    "active": true,
                    "noBattery": false,
                    "id": 16,
                    "type": "HEATING",
                    "accTypeBoiler": "SWITCH",
                    "boilerTempSupport": false,
                    "modeTimer": 30,
                    "separateTemperature": false,
                    "separateHumidity": true,
                    "autoOffDelay": false,
                    "openWindowSensor": true,
                    "easyMode": false,
                    "airQuality": false,
                    "delaySwitch": false
                }
            ],
            "id": 559344,
            "temperatureUnit": "CELSIUS",
            "extras": {
                "runningInformation": false,
                "accTypePresenceLock": "SWITCH",
                "boostSwitch": false,
                "presenceLock": false,
                "sheduleSwitch": true,
                "centralSwitch": true,
                "childLockSwitches": [
                    {
                        "name": "Diele XXX",
                        "serialNumber": "XXX",
                        "active": false
                    },
                    {
                        "name": "Bad Erdgeschoss XXX",
                        "serialNumber": "XXX",
                        "active": false
                    },
                    {
                        "name": "Wohnzimmer XXX",
                        "serialNumber": "XXX",
                        "active": false
                    },
                    {
                        "name": "Wohnzimmer XXX",
                        "serialNumber": "XXX",
                        "active": false
                    },
                    {
                        "name": "Laras Zimmer XXX",
                        "serialNumber": "XXX",
                        "active": false
                    },
                    {
                        "name": "Spielzimmer XXX",
                        "serialNumber": "XXX",
                        "active": false
                    },
                    {
                        "name": "Raphis Zimmer XXX",
                        "serialNumber": "XXX",
                        "active": false
                    },
                    {
                        "name": "Büro XXX",
                        "serialNumber": "XXX",
                        "active": false
                    },
                    {
                        "name": "Büro XXX",
                        "serialNumber": "XXX",
                        "active": false
                    },
                    {
                        "name": "Bad Obergeschoss XXX",
                        "serialNumber": "XXX",
                        "active": false
                    },
                    {
                        "name": "Bad Obergeschoss XXX",
                        "serialNumber": "XXX",
                        "active": false
                    },
                    {
                        "name": "Schlafzimmer XXX",
                        "serialNumber": "XXX",
                        "active": false
                    },
                    {
                        "name": "Schlafzimmer XXX",
                        "serialNumber": "XXX",
                        "active": false
                    },
                    {
                        "name": "Bad Dachgeschoss XXX",
                        "serialNumber": "XXX",
                        "active": false
                    },
                    {
                        "name": "Bad Dachgeschoss XXX",
                        "serialNumber": "XXX",
                        "active": false
                    },
                    {
                        "name": "Garderobe XXX",
                        "serialNumber": "XXX",
                        "active": false
                    },
                    {
                        "name": "Hobbyraum XXX",
                        "serialNumber": "XXX",
                        "active": false
                    }
                ],
                "turnoffSwitch": false
            },
            "weather": {
                "temperatureSensor": false,
                "solarIntensity": false,
                "airQuality": false
            },
            "geolocation": {
                "latitude": "***",
                "longitude": "***"
            },
            "polling": 30,
            "presence": {
                "user": [
                    {
                        "accType": "OCCUPANCY",
                        "active": false,
                        "name": "***"
                    },
                    {
                        "accType": "OCCUPANCY",
                        "active": false,
                        "name": "***"
                    }
                ],
                "anyone": false,
                "accTypeAnyone": "OCCUPANCY"
            },
            "telegram": {
                "messages": {
                    "openWindow": {},
                    "presence": {}
                },
                "active": false
            },
            "password": "***",
            "name": "***",
            "username": "***"
        }
    ]
}

**Comment by SeydX** [comment]
@spooky82 

u have ``"mode": "AUTO"``  

This means, every change made to the thermostat will be done in the AUTO mode. 

Change it to ``"mode": "MANUAL"``  and it should be fine. You can always change the thermostat back in to "AUTO" state by choosing "AUTOMATIC" within the thermostat accessory

**Comment by spooky82** [comment]
@SeydX 

Nope, still the same: I changed mode for all zones to MANUAL, but still no impact on the Schedule Switch in Homekit.

What I want to achieve is that this switch reflects the current state of my tado system.

**Comment by SeydX** [comment]
Ahhh, u dont mean with switch the "AUTOMATIC" state from a thermostat.

U mean the shedule switch (from central switch) itself.

Yes u misunderstand something. The shedule switch dont represent a state. It is online a toggle switch. Like the shedule switch (quick action) from tado itself. It only switches all thermostats into shedule mode

After the trigger, it switches off
