### ISSUE TITLE
Light Sensor

### ISSUE THREAD

**Issue by adamrzanek** [SeydX/homebridge-tado-platform#54]
First - thanks for great work! You plugin is the state of art! 
I have a question. Is it possible for you to expose Solar Intensity as light sensor rather then Bulb? It’s the only thing that’s bother me :)
Thanks Again

**Comment by SeydX** [comment]
@adamrzanek 

added in v6.0.9. 

Just add ``"accTypeSolarIntensity": "SENSOR"`` to the weather block in your config.json or set it up via config ui x

https://github.com/SeydX/homebridge-tado-platform/blob/master/README.md#dummy-switch
