### ISSUE TITLE
It is possible to disable both switches in Presence Lock Accessory while in switch mode

### ISSUE THREAD

**Issue by Ilkase7en** [SeydX/homebridge-tado-platform#55]
Having the 'Presence Lock Accessory Type' set to 'switch' the change between home and away works only if I click on the disabled switch (being at home(on) and click on away(off)) to activate. Clicking on the enabled one disables both states 'home' and 'away' and both set to off state at the same time.

**Comment by SeydX** [comment]
Presence lock (switch) exposes two switches to homekit. Home an Away

You can only enable one. Thats the reason why the other switch turns off when u enable one. And if you switch both off, you will activate the auto mode

**Comment by Ilkase7en** [comment]
So, it will go to auto mode instantly (while both switches are turned off) and after a new interval checking the tado website by the plugin it will update the switches to either home or away depending on the current situation? While they change instantly when clicking on the disabled one cause, there is no feedback loop with the website.

**Comment by SeydX** [comment]
> So, it will go to auto mode instantly (while both switches are turned off) and after a new interval checking the tado website by the plugin it will update the switches to either home or away depending on the current situation? 

The switches dont turn on/off depending on YOUR position. It turns on/off depending on the Geofency switch in the tado app.

> While they change instantly when clicking on the disabled one cause, there is no feedback loop with the website.

Idk what u mean exactly here, but on my system it works flawlessly. Can u provide a screenshot maybe from what u mean?

**Comment by Ilkase7en** [comment]
> > While they change instantly when clicking on the disabled one cause, there is no feedback loop with the website.
> 
> Idk what u mean exactly here, but on my system it works flawlessly. Can u provide a screenshot maybe from what u mean?

I use them the other way around. If HK detects that the last person left the house I activate the away switch to set tado in away mode. If the first person comes back home I set the switch to home active and auto mode is running again. Instead of reading the values I set them using the dual switch.

**Comment by SeydX** [comment]
What I didn't understand, what would you have liked to have been different?

There is also a „presence“ function you can use for this kind of automation

**Comment by Ilkase7en** [comment]
> What I didn't understand, what would you have liked to have been different?

Initially, I was wondering about the behavior of the dual switch. Because I use them as active switches to set home and away as the home and away feature is not available without having a paid subscription. Before your plugin update I did this using API web calls in HK. But using your plugin it is much more convenient having no API calls inside an automation and just filp the switches. But now I learned this is not the origin use they are designed for.

> There is also a „presence“ function you can use for this kind of automation

If I look at the configuration the presence function uses a sensor to show the status, but I'm not able to change the exposed sensor using an automation.

**Comment by SeydX** [comment]
> Initially, I was wondering about the behavior of the dual switch. Because I use them as active switches to set home and away as the home and away feature is not available without having a paid subscription.[...] But now I learned this is not the origin use they are designed for.

Allright, im closing this then
