### ISSUE TITLE
No plugin was found...

### ISSUE THREAD

**Issue by T-Bone90** [SeydX/homebridge-tado-platform#56]
Hey

with the newest version (6.0.7) I get
`No plugin was found for the platform "TadoPlatform" in your config.json. Please make sure the corresponding plugin is installed correctly.`
And I don't see my Tado setup in Homekit.

Best regards

**Comment by SeydX** [comment]
@T-Bone90 

Hey, im so sry, my mistake.. 

v6.0.8 is online and should fix it

**Comment by T-Bone90** [comment]
Yes is fixed now thank you! ;)

**Comment by T-Bone90** [comment]
(sorry for my bad English)
What else I can think of. I either get a message indicating that it is being heated (orange) or that it is being cooled (blue). I don't get any green display.
Even when the temperature is reached, it says "is being cooled" ...
Is it wanted like that?
