### ISSUE TITLE
Feature Request: Dummy Window Switch

### ISSUE THREAD

**Issue by Nastras** [SeydX/homebridge-tado-platform#59]
Already present in the old plugin, now unfortunately missing 😅

The window switch as a dummy switch under the central switch is needed for contact sensor based automations to be set as a condition.

Through these conditions the fresh air automations can be switched off at any time.

Would be great if you would implement this again. Thank you!
Ps. Further details I have written to you in the forum.

**Comment by SeydX** [comment]
Added in v6.0.9

https://github.com/SeydX/homebridge-tado-platform/blob/master/README.md#dummy-switch

**Comment by Nastras** [comment]
There is still a problem with the dummy switch.
It does not save its status after a restart of the HB.
Can you still implement this?

**Comment by SeydX** [comment]
Fixed in v6.0.10

**Comment by Nastras** [comment]
👌 Thx
