### ISSUE TITLE
Not all radiator thermostats discovered

### ISSUE THREAD

**Issue by henkhb** [SeydX/homebridge-tado-platform#6]
The Plugin exposes only one of my two smart radiators to HomeKit. 
The one not discovered is on firmware 54.4, the working one on 49.3 ... maybe this is the reason?

**Comment by henkhb** [comment]
New HW revision of radiator thermostats out. Need to edit platform.js like this:

}
if(self.config.radiatorThermostat&&!self.config.onePerRoom){
configArray.push({
type: 'HEATING',
deviceType: 'VA02',
thermoType: self.types.radiatorThermostat
});

**Comment by mylesgray** [comment]
If you want to test the fix:

`npm -g uninstall homebridge-tado-platform`

then run:

`npm -g install git+https://git@github.com/mylesgray/homebridge-tado-platform.git#feature\/new-hardware-revisions --unsafe-perms`

**Comment by SeydX** [comment]
Im currently working on v5. Should be fixed now
