### ISSUE TITLE
Error: Cannot find property of 'Celcius'

### ISSUE THREAD

**Issue by djfanatix** [SeydX/homebridge-tado-platform#60]
I tried to setup the app with config-x-uit, but I always get the error:
Error: Cannot find property of 'Celcius' of undefined

**Comment by SeydX** [comment]
I wil check this

**Comment by SeydX** [comment]
@djfanatix 

where do you get this msg exactly? In the log? Browser?

**Comment by djfanatix** [comment]
In the browser of the config-x.

Fyi
I just did the manual config, which works fine.
