### ISSUE TITLE
Errors after update with easymode

### ISSUE THREAD

**Issue by T-Bone90** [SeydX/homebridge-tado-platform#61]
@SeydX thank you for the newest updates but I get errors and it doesn't work for me.
I have easy mode enabled.

TypeError: Cannot read property 'getCharacteristic' of undefined at /usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:1022:24 at Array.forEach (<anonymous>) at updateZones (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:900:29) at processTicksAndRejections (internal/process/task_queues.js:93:5) at getStates (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:699:9) [22.3.2021, 17:08:39] [TadoPlatform] TypeError: Cannot read property 'getCharacteristic' of undefined at /usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:1022:24 at Array.forEach (<anonymous>) at updateZones (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:900:29) at processTicksAndRejections (internal/process/task_queues.js:93:5) at getStates (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:699:9) TypeError: Cannot read property 'getCharacteristic' of undefined at /usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:1022:24 at Array.forEach (<anonymous>) at updateZones (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:900:29) at processTicksAndRejections (internal/process/task_queues.js:93:5) at getStates (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:699:9) [22.3.2021, 17:09:10] [TadoPlatform] TypeError: Cannot read property 'getCharacteristic' of undefined at /usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:1022:24 at Array.forEach (<anonymous>) at updateZones (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:900:29) at processTicksAndRejections (internal/process/task_queues.js:93:5) at getStates (/usr/local/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:699:9)

Red Rooms are the same (original Tado and your plugin) and purple rooms are the same.
The Thermostat in "Badezimmer" is 20°. Your plugin shows "AUS/OFF"
The same with "Wohnzimmer".

**Comment by SeydX** [comment]
thx i will check this

**Comment by SeydX** [comment]
Fix comes with next version
