### ISSUE TITLE
Error: illegal value for Current Ambient Light Level

### ISSUE THREAD

**Issue by nielsth** [SeydX/homebridge-tado-platform#62]
Homebridge log reads the following error:
`[3/22/2021, 18:19:50] [homebridge-tado-platform] This plugin generated a warning from the characteristic 'Current Ambient Light Level': characteristic was supplied illegal value: number 0 exceeded minimum of 0.0001. See https://git.io/JtMGR for more info.`

In the config I enabled `solarIntensity` and for `accTypeSolarIntensity` I chose `"SENSOR"`

Running Homebridge version 1.3.4, and plug-in version 6.0.10

**Comment by SeydX** [comment]
Oh, will check this ty

**Comment by SeydX** [comment]
Fixed with https://github.com/SeydX/homebridge-tado-platform/commit/3fc49c6540c44689695c2a4a2ee3603dbf0eacba
