### ISSUE TITLE
Error on setup still remians after latest update

### ISSUE THREAD

**Issue by boomcreativemartin** [SeydX/homebridge-tado-platform#66]
@SeydX thank you for trying to fix the error that comes up with cannot assign celcius to undefinedl, unfortunately, it's still occurring.

Below is a ss of the error message.
<img width="1440" alt="Screenshot 2021-03-22 at 21 06 28" src="https://user-images.githubusercontent.com/63953349/112058449-83d0a400-8b52-11eb-9645-78dabe3044a4.png">

this is with  homebridge-tado-platform v6.0.11

**Comment by SeydX** [comment]
@boomcreativemartin 

can u remove browser cache and try again pls?

**Comment by boomcreativemartin** [comment]
I can confirm that it works after the cache refresh

Warmest Regards,
Martin


Martin Suker
Creative Director
BOOM. Creative Ltd
***@***.***
07835200375 makeaboom.uk
119 Roman Road
London E2 0QN
This communication and the information it contains is intended for the person or organisation to whom it is addressed. Its contents are confidential and may be protected in law. Unauthorised use, copying or disclosure of any of it may be unlawful. If you are not the intended recipient, please contact us immediately by replying to this email. Opinions, conclusions and other information in this message that do not relate to the official business of BOOM. Creative Ltd and shall be understood as neither given nor endorsed by it. The contents of any attachments in this e-mail may contain software viruses, which could damage your own computer system. Whilst BOOM. Creative Ltd have taken every reasonable precaution to minimise this risk, we cannot accept liability for any damage which you sustain as a result of software viruses.

**Comment by boomcreativemartin** [comment]
Sorry do you mind deleting my signature info from the request on GitHub, forgot to hide that :/

Thank you for all you do!

**Comment by SeydX** [comment]
sure :)
