### ISSUE TITLE
Enhancement: Binary Air Quality sensors

### ISSUE THREAD

**Issue by nielsth** [seydx/homebridge-tado-platform#67]
The new (outdoor) Air Quality sensor is greatly appreciated. HomeKit also supports binary air quality sensors, which have options to set-up notifications and can be used as a trigger for automations. An example are Netatmo's Indoor modules, which are listed as a binary CO2 sensor which is triggered when a bad air quality threshold is reached. Such notifications can be good reminders to keep windows closed for a while. 

Would you consider adding optional binary sensors for the outdoor air quality pollutants that are now combined under the Air Quality sensor? (NO2, Ozone, PM2.5, PM10 and SO2?)

Under the Details of such sensors, usually the triggered state is shown (either Yes or No) and the Current value.

Here are some images of how the Netatmo Indoor module shows up as a binary sensor for CO2 in the Home app (it is also still listed as an Air Quality sensor, under the combined climate info at the top of the room):
![IMG_8F20FE67198A-1 2](https://user-images.githubusercontent.com/13969232/112067264-10399180-8b68-11eb-93c2-03ace5ee8384.jpeg)
![IMG_526F0E1930DE-1](https://user-images.githubusercontent.com/13969232/112067276-129beb80-8b68-11eb-832c-e40e0019e2c6.jpeg)
![IMG_4265C6380197-1](https://user-images.githubusercontent.com/13969232/112067279-13cd1880-8b68-11eb-9eea-1e5a8a1f4cc6.jpeg)

**Comment by SeydX** [comment]
Soo much feature request in just one day :D 

Thx, will add this to my todo list

**Comment by nielsth** [comment]
Yeah, I gave it a good test today after updating to v6. Love this plug-in. It packs a ton of stuff tado left out of their HomeKit integration.

**Comment by nielsth** [comment]
I recently learned that the HomeKit framework only supports a binary sensor for CO2 (and smoke and CO). Not for air quality and the pollutants listed above. Therefor I'll close this request.
