### ISSUE TITLE
Units of air quality data

### ISSUE THREAD

**Issue by nielsth** [SeydX/homebridge-tado-platform#68]
The air quality sensor reports measured values in a different unit than the tado app does. Tado reports Ozone, SO2, CO and No2 in ppb instead of μg/m3. 

Also, while 'm getting quite different values between the tado app and the sensor from this plug-in. Something worth looking into?

![IMG_8296](https://user-images.githubusercontent.com/13969232/112069674-8cce6f00-8b6c-11eb-9a61-92ac2672ac51.PNG)
![IMG_8297](https://user-images.githubusercontent.com/13969232/112069686-8e983280-8b6c-11eb-8561-0d5712c7d902.jpg)

**Comment by SeydX** [comment]
Hey @nielsth 

thats a HomeKit thing. 

I can not change the units, therefore i need to convert the value into ug/m3

**Comment by nielsth** [comment]
That was fast! Weird that HomeKit doesn't support ppb here, as binary CO2 sensors in HomeKit do report the current value in ppb. I might make a feature request in Apple's Feedback Assistant in that case, as these conversions might not be ideal from what I've read a long time ago.
