### ISSUE TITLE
Boiler not discovered

### ISSUE THREAD

**Issue by DSchumacher2104** [SeydX/homebridge-tado-platform#7]
My boiler has the following config ('RU01' instead of 'BU01'), which is not discovered by the plugin:

 {
 "id":0,
 "name":"Warmwasser",
 "type":"HOT_WATER",
 "dateCreated":"...",
 "deviceTypes":["RU01"],
 "devices":
 [
 {
 "deviceType":"RU01",
 "serialNo":"RUxxxxxxxxxx",
 "shortSerialNo":"RUxxxxxxxxxx",
 "currentFwVersion":"49.4",
 "connectionState":{"value":true,"timestamp":"..."},
 "characteristics":{"capabilities":["INSIDE_TEMPERATURE_MEASUREMENT","IDENTIFY","OPEN_WINDOW_DETECTION"]},
 "batteryState":"NORMAL",
 "duties":["ZONE_UI","ZONE_DRIVER","ZONE_LEADER"]
 }
 ],
 "reportAvailable":false,
 "supportsDazzle":false,
 "dazzleEnabled":false,
 "dazzleMode":{"supported":false},
 "openWindowDetection":{"supported":false}
 }

**Comment by SeydX** [comment]
Hey, i opened a new issue with instructions to test the beta version!

https://github.com/SeydX/homebridge-tado-platform/issues/16

**Comment by SeydX** [comment]
should be fixed in v5
