### ISSUE TITLE
After upgrading to 6.0.11 "ReferenceError: Cannot access 'service' before initialization"

### ISSUE THREAD

**Issue by jotzet79** [SeydX/homebridge-tado-platform#70]
0|homebridge  | [27.3.2021, 15:01:05] [MyHome TadoPlatform] ReferenceError: Cannot access 'service' before initialization
0|homebridge  |     at /home/pi/.nvm/versions/node/v14.16.0/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:1279:93
0|homebridge  |     at Array.forEach (<anonymous>)
0|homebridge  |     at updateZones (/home/pi/.nvm/versions/node/v14.16.0/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:1275:45)
0|homebridge  |     at runMicrotasks (<anonymous>)
0|homebridge  |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
0|homebridge  |     at getStates (/home/pi/.nvm/versions/node/v14.16.0/lib/node_modules/homebridge-tado-platform/src/helper/handler.js:699:9)

Do I have a wrong configuration which causes this?

**Comment by SeydX** [comment]
Hm can u post your config pls

i will check this

**Comment by T-Bone90** [comment]
Sure

>         {
            "platform": "TadoPlatform",
            "name": "TadoPlatform",
            "homes": [
                {
                    "id": xxxxxx,
                    "name": "Mein Zuhause",
                    "username": "xxxxxxxxx",
                    "password": "xxxxxxxxxx",
                    "polling": 30,
                    "temperatureUnit": "CELSIUS",
                    "geolocation": {
                        "longitude": "xxxxxxx",
                        "latitude": "xxxxxxxxx"
                    },
                    "presence": {
                        "anyone": false,
                        "accTypeAnyone": "OCCUPANCY",
                        "user": [
                            {
                                "active": false,
                                "name": "xxxx",
                                "accType": "OCCUPANCY"
                            },
                            {
                                "active": false,
                                "name": "xxxx",
                                "accType": "OCCUPANCY"
                            }
                        ]
                    },
                    "weather": {
                        "temperatureSensor": false,
                        "solarIntensity": false,
                        "airQuality": false
                    },
                    "extras": {
                        "centralSwitch": false,
                        "runningInformation": false,
                        "presenceLock": false,
                        "accTypePresenceLock": "ALARM",
                        "boostSwitch": false,
                        "sheduleSwitch": false,
                        "turnoffSwitch": false,
                        "childLockSwitches": [
                            {
                                "active": false,
                                "name": "Arbeitszimmer xxxxx",
                                "serialNumber": "xxxxx"
                            },
                            {
                                "active": false,
                                "name": "Badezimmer xxxxx",
                                "serialNumber": "xxxxx"
                            },
                            {
                                "active": false,
                                "name": "Wohnzimmer xxxxx",
                                "serialNumber": "xxxxx"
                            },
                            {
                                "active": false,
                                "name": "Wohnzimmer xxxxx",
                                "serialNumber": "xxxxx"
                            }
                        ]
                    },
                    "zones": [
                        {
                            "active": true,
                            "id": 4,
                            "name": "Arbeitszimmer",
                            "delaySwitch": false,
                            "autoOffDelay": false,
                            "openWindowSensor": true,
                            "openWindowSwitch": false,
                            "airQuality": false,
                            "separateTemperature": false,
                            "separateHumidity": false,
                            "minStep": "1",
                            "minValue": 5,
                            "maxValue": 25,
                            "mode": "MANUAL",
                            "modeTimer": 30,
                            "easyMode": false,
                            "noBattery": true,
                            "type": "HEATING",
                            "boilerTempSupport": false,
                            "accTypeBoiler": "SWITCH"
                        },
                        {
                            "active": true,
                            "id": 5,
                            "name": "Badezimmer",
                            "delaySwitch": false,
                            "autoOffDelay": false,
                            "openWindowSensor": true,
                            "openWindowSwitch": false,
                            "airQuality": false,
                            "separateTemperature": false,
                            "separateHumidity": false,
                            "minStep": "1",
                            "minValue": 5,
                            "maxValue": 25,
                            "mode": "MANUAL",
                            "modeTimer": 30,
                            "easyMode": false,
                            "noBattery": true,
                            "type": "HEATING",
                            "boilerTempSupport": false,
                            "accTypeBoiler": "SWITCH"
                        },
                        {
                            "active": true,
                            "id": 6,
                            "name": "Wohnzimmer",
                            "delaySwitch": false,
                            "autoOffDelay": false,
                            "openWindowSensor": true,
                            "openWindowSwitch": false,
                            "airQuality": false,
                            "separateTemperature": false,
                            "separateHumidity": false,
                            "minStep": "1",
                            "minValue": 5,
                            "maxValue": 25,
                            "mode": "MANUAL",
                            "modeTimer": 30,
                            "easyMode": false,
                            "noBattery": true,
                            "type": "HEATING",
                            "boilerTempSupport": false,
                            "accTypeBoiler": "SWITCH"
                        }
                    ],
                    "telegram": {
                        "active": false
                    }
                }
            ]
        }

**Comment by jotzet79** [comment]
"username": "username",
            "password": "thanks-seydx-for-ally-our-efforts",
            "homeName": "MyHome",
            "areOccupancySensorsEnabled": true,
            "isGlobalHomeAwayEnabled": true,
            "isAutoAssistEnabled": false,
            "areWindowSensorsHidden": false,
            "switchToAutoInNextTimeBlock": true,
            "isAlternativeStateLogicEnabled": false,
            "zones": [
                {
                    "zoneId": 3,
                    "zoneName": "Sleep"
                },
                {
                    "zoneId": 4,
                    "zoneName": "Chill"
                },
                {
                    "zoneId": 5,
                    "zoneName": "Come"
                },
                {
                    "zoneId": 6,
                    "zoneName": "Work"
                }
            ],
            "platform": "TadoPlatform",
            "homes": [
                {
                    "id": 295967,
                    "name": "JoSaHome",
                    "username": "username",
                     "password": "thanks-seydx-for-ally-our-efforts",
                    "polling": 30,
                    "temperatureUnit": "CELSIUS",
                    "geolocation": {
                        "longitude": "lon",
                        "latitude": "lat"
                    },
                    "presence": {
                        "anyone": true,
                        "accTypeAnyone": "OCCUPANCY",
                        "user": [
                            {
                                "active": false,
                                "name": "JotPhone",
                                "accType": "OCCUPANCY"
                            },
                            {
                                "active": false,
                                "name": "JotPhoneBiz",
                                "accType": "OCCUPANCY"
                            },
                            {
                                "active": false,
                                "name": "SZ",
                                "accType": "OCCUPANCY"
                            },
                            {
                                "active": false,
                                "name": "MyPad",
                                "accType": "OCCUPANCY"
                            }
                        ]
                    },
                    "weather": {
                        "temperatureSensor": true,
                        "solarIntensity": true,
                        "accTypeSolarIntensity": "SENSOR",
                        "airQuality": true
                    },
                    "extras": {
                        "centralSwitch": true,
                        "runningInformation": true,
                        "presenceLock": true,
                        "accTypePresenceLock": "ALARM",
                        "boostSwitch": true,
                        "sheduleSwitch": true,
                        "turnoffSwitch": true,
                        "dummySwitch": true,
                        "childLockSwitches": [
                            {
                                "active": false,
                                "name": "Chill VA1234567",
                                "serialNumber": "VA1234567"
                            },
                            {
                                "active": false,
                                "name": "Work VA1234567",
                                "serialNumber": "VA1234567"
                            },
                            {
                                "active": false,
                                "name": "Sleep VA1234567",
                                "serialNumber": "VA1234567"
                            },
                            {
                                "active": false,
                                "name": "Come VA1234567",
                                "serialNumber": "VA1234567"
                            }
                        ]
                    },
                    "zones": [
                        {
                            "active": true,
                            "id": 4,
                            "name": "Chill",
                            "delaySwitch": false,
                            "autoOffDelay": false,
                            "openWindowSensor": true,
                            "openWindowSwitch": true,
                            "airQuality": true,
                            "separateTemperature": true,
                            "separateHumidity": true,
                            "mode": "AUTO",
                            "modeTimer": 30,
                            "easyMode": false,
                            "noBattery": false,
                            "type": "HEATING",
                            "boilerTempSupport": false,
                            "accTypeBoiler": "SWITCH"
                        },
                        {
                            "active": true,
                            "id": 6,
                            "name": "Work",
                            "delaySwitch": false,
                            "autoOffDelay": false,
                            "openWindowSensor": true,
                            "openWindowSwitch": true,
                            "airQuality": true,
                            "separateTemperature": true,
                            "separateHumidity": true,
                            "mode": "AUTO",
                            "modeTimer": 30,
                            "easyMode": false,
                            "noBattery": false,
                            "type": "HEATING",
                            "boilerTempSupport": false,
                            "accTypeBoiler": "SWITCH"
                        },
                        {
                            "active": true,
                            "id": 3,
                            "name": "Sleep",
                            "delaySwitch": false,
                            "autoOffDelay": false,
                            "openWindowSensor": true,
                            "openWindowSwitch": true,
                            "airQuality": true,
                            "separateTemperature": true,
                            "separateHumidity": true,
                            "mode": "AUTO",
                            "modeTimer": 30,
                            "easyMode": false,
                            "noBattery": false,
                            "type": "HEATING",
                            "boilerTempSupport": false,
                            "accTypeBoiler": "SWITCH"
                        },
                        {
                            "active": true,
                            "id": 5,
                            "name": "Come",
                            "delaySwitch": false,
                            "autoOffDelay": false,
                            "openWindowSensor": true,
                            "openWindowSwitch": true,
                            "airQuality": true,
                            "separateTemperature": true,
                            "separateHumidity": true,
                            "mode": "AUTO",
                            "modeTimer": 30,
                            "easyMode": false,
                            "noBattery": false,
                            "type": "HEATING",
                            "boilerTempSupport": false,
                            "accTypeBoiler": "SWITCH"
                        }
                    ],
                    "telegram": {
                        "active": false
                    }
                }
            ],
            "name": "MyHome TadoPlatform"
        }
    ],

**Comment by TimvanNuland** [comment]
Thanks a lot for this great plugin! I have the same issue in my homebridge log. It seems to be related to whether I have any "openWindowSwitch" set to "true". Does this help you?

**Comment by SeydX** [comment]
Fixed in v6.0.12

**Comment by jotzet79** [comment]
Working fine again, thanks!
