### ISSUE TITLE
Humidity is not showing

### ISSUE THREAD

**Issue by seb2010** [SeydX/homebridge-tado-platform#78]
I am using the homebridge-tado-platform in the HAM-adapter in IOBroker and after the recent update of the adapter and this plugin here, the current relative humidity is 0 for every zone. I do not kknow if this is an issue with the IOBroker adapter or this plugin here. The Tado API v2 is giving me the humidity values just fine....

**Comment by SeydX** [comment]
Hm i can not reproduce this issue. Can u post your config pls? and can u enable debug in config.json and restart homebridge.
