### ISSUE TITLE
Incorrect temperature 

### ISSUE THREAD

**Issue by alszaitsev** [SeydX/homebridge-tado-platform#79]
Hi. One of the devices shows incorrect temperature (-2.0C’ while actual is 28C’), although in Tado app everything is ok with measurements. This a smart thermostat, firmware 54.20

**Comment by alszaitsev** [comment]
Additional info. Now another device is showing incorrect info -also temperature below 0’C (the first one now shows the correct temperature ).

**Comment by alszaitsev** [comment]
I think I've found the problem. I have Celcius chosen but by some reason the accessory is providing a temperature in Fahrenheit (calculating the correct temperature from the sensor in Celsius). Please check

**Comment by SeydX** [comment]
Should be fixed in v6.0.13

**Comment by JarFiles** [comment]
Unfortunately, this is still happening for me

**Comment by SeydX** [comment]
@JarFiles 

can u try v6.0.14 pls

**Comment by alszaitsev** [comment]
6.0.14 works great. Thank you!
