### ISSUE TITLE
Cannot change temperature when in Auto Mode

### ISSUE THREAD

**Issue by jacoscar** [SeydX/homebridge-tado-platform#9]
I understand this might have been intentional, but when using the Tado Bridge V3 with the proper homekit this works like a charm, when using homebridge and you try and change the temperature using siri while in auto mode you get a message in the command window saying "you cant change temperature while in auto mode".
Is there any reason why this cannot work (i.e. switch to manual control and set the temperature with one action)?
Why do we need the "cool" mode on a thermostat anyway?

**Comment by SeydX** [comment]
Im currently working on v5. Should be fixed now

**Comment by SeydX** [comment]
Hey, i opened a new issue with instructions to test the beta version!

https://github.com/SeydX/homebridge-tado-platform/issues/16

**Comment by SeydX** [comment]
should be fixed in v5

**Comment by paradeiser** [comment]
I still have this behaviour:
When I set a manual temperature using Home.app while in "Automatic" Mode, it just jumps back to the pre-set temperature after a few seconds. No manual set is possible.

What I would expect: Automatically change mode to manual and set given temperature (using dial in home.app), and when "overrideMode" is set to "auto" tado will just go back to normal on the next sheduled change.
Current work-around: First set mode to "cool" then set a specific temperature (even higher). Then tado sets the right temperature (until next sheduled change when overrideMode is auto).

iOS 13
homebridge-tado-platform v5.1.6 
Bridge fw v47.2
